
version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    # env_file:
    #   - ./backend/.env
    depends_on:
      - database

  database:
    image: redis:latest
    ports:
      - 6379:6379

  frontend:
    build:
      context: ./frontend/my-app
    ports:
      - 3000:3000
    volumes:
      - ./frontend/my-app:/app
    # environment:
    #   - NODE_ENV=production
    depends_on:
      - backend


### Future reference:
# Rebuild a component: 
#     docker-compose build --no-cache <service-name>
#     docker-compose build <service-name>