
version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    # environment:
    #   - NODE_ENV=production
    # depends_on:
    #   - database

  # database:
  #   image: mysql:latest
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=secret
  #     - MYSQL_DATABASE=mydb
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=password

# frontend:
#   build:
#     context: .
#     dockerfile: Dockerfile
#   ports:
#     - 3000:3000
#   volumes:
#     - ./frontend:/app/frontend
#   environment:
#     - NODE_ENV=production
#   depends_on:
#     - backend
